config/routes.rb
Rails.application.routes.draw do
  root 'robes#index'
  resources :robes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/robe.rb
# require 'knn'
class Robe < ApplicationRecord

  def nearest_neighbours(data, nb_neighbours)
    # take the complete feature vector data set, and the number of neighbours.
    # give an array with the index (in the array) of the nearest neighbours

    knn = KNN.new(data)

    neighbours = knn.nearest_neighbours(JSON.parse(self.feature_vector), nb_neighbours)

    neighbours_id = []
    neighbours.each do |neigh|
      neighbours_id << neigh[0]
    end

    return neighbours_id

  end

end

class KNN
  def initialize(data, options={})
    @data = data
    @distance_measure = options[:distance_measure] || :euclidean_distance
  end

  def nearest_neighbours(input, k=4)
    find_closest_data(input, k)
  end

  private

  def find_closest_data(input, k)
    begin
      calculated_distances = []

      @data.each_with_index do |datum, index| #Ye olde english
        # distance = input.send(@distance_measure, datum)
        distance = 0
        for i in 0..( input.length-1 )
          distance = distance + (input[i] - datum[i])**2
        end
        distance = distance**(0.5)
        calculated_distances << [index, distance, datum]
      end

      calculated_distances.sort {|x, y| x[1] <=> y[1]}.first(k)
    rescue NoMethodError
      raise "Hey, that's not a measurement. Read the README for available measurements"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/robes_controller.rb
class RobesController < ApplicationController
  def index
    puts "1°°°°"
    data = get_all_vector_features[:data]
    puts "4°°°°"
    index_dress = get_all_vector_features[:index_dress]
    puts "5 °°°°°"
    @robe_chosen = Robe.find(rand(1..100)) # attention
    array_nearest_neighbours = @robe_chosen.nearest_neighbours(data, 9)

    index_neighbours = []
    array_nearest_neighbours.each do |ind|
      index_neighbours << index_dress[ind]
    end

    @robe_neighbours = Robe.find(index_neighbours)

    render "index"
  end

  def show

    data = get_all_vector_features[:data]
    index_dress = get_all_vector_features[:index_dress]

    @robe_chosen = Robe.find(params[:id]) # attention
    array_nearest_neighbours = @robe_chosen.nearest_neighbours(data, 9)

    index_neighbours = []
    array_nearest_neighbours.each do |ind|
      index_neighbours << index_dress[ind]
    end

    @robe_neighbours = Robe.find(index_neighbours)

    render "index"

  end

  def get_all_vector_features

    # fill a data array with all feature vectors from the Robe database
    data = []
    index_dress = []
    Robe.find_each do |dress|
      data << JSON.parse(dress.feature_vector)
      index_dress << dress.id
    end
    puts data[10][6]
    puts "3°°°°"
    return { data: data, index_dress: index_dress }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robes_helper.rb
module RobesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Dress
    = csrf_meta_tags
    = stylesheet_link_tag  'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css', media: 'all'

    = javascript_include_tag 'application', 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'
  %body
    = yield

app/views/robes/index.html.haml
.container-fluid.content
  .row.content
    .col
      = link_to image_tag(@robe_chosen.url, size: "500x700"), robe_path(@robe_chosen)

    .col
      .row
        .col
          = link_to image_tag(@robe_neighbours[0].url, size: "180x250"), robe_path(@robe_neighbours[0])
        .col
          = link_to image_tag(@robe_neighbours[1].url, size: "180x250"), robe_path(@robe_neighbours[1])
        .col
          = link_to image_tag(@robe_neighbours[2].url, size: "180x250"), robe_path(@robe_neighbours[2])
      .row
        .col
          = link_to image_tag(@robe_neighbours[3].url, size: "180x250"), robe_path(@robe_neighbours[3])
        .col
          = link_to image_tag(@robe_neighbours[4].url, size: "180x250"), robe_path(@robe_neighbours[4])
        .col
          = link_to image_tag(@robe_neighbours[5].url, size: "180x250"), robe_path(@robe_neighbours[5])
      .row
        .col
          = link_to image_tag(@robe_neighbours[6].url, size: "180x250"), robe_path(@robe_neighbours[6])
        .col
          = link_to image_tag(@robe_neighbours[7].url, size: "180x250"), robe_path(@robe_neighbours[7])
        .col
          = link_to image_tag(@robe_neighbours[8].url, size: "180x250"), robe_path(@robe_neighbours[8])